In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [18]:
df1 = pd.Series([1,2,3,4,5,6])

In [19]:
df1

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [20]:
df2 = df1.to_list()
df2

[1, 2, 3, 4, 5, 6]

In [23]:
df3 = pd.Series([3,4,5,6,7,8])
df3

0    3
1    4
2    5
3    6
4    7
5    8
dtype: int64

In [31]:
df4 = df1+df3

In [32]:
df4

0     4
1     6
2     8
3    10
4    12
5    14
dtype: int64

In [37]:
ds1=np.array(df1) #or df1.values

ds1

array([1, 2, 3, 4, 5, 6])

In [39]:
ds2 = pd.Series(ds1)
ds2

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [137]:
s = pd.Series(['1','2', 'Python', '3.2', '4','10.1'])
print("Original Data Series:")
print(s)

new_s = s.sort_values()
print(new_s)

# ser1 = pd.to_numeric(ser, errors = 'coerce')

# ser2 = ser1.astype('int64')
# print(ser2)

 
# ser1.sort_values(ascending = True)


Original Data Series:
0         1
1         2
2    Python
3       3.2
4         4
5      10.1
dtype: object
0         1
5      10.1
1         2
3       3.2
4         4
2    Python
dtype: object


In [43]:
df = pd.to_numeric(ser, errors = 'coerce') #coerce will help to parce python string as NaN and wont raise any errors. 

df

0    1.0
1    2.0
2    3.0
3    NaN
4    1.2
5    4.0
dtype: float64

In [56]:
df = pd.DataFrame({'col1': [1,2], 'col2': [3,4]})

df

col1  col2
0     1     3
1     2     4

## Convert a particular column to series

In [59]:
# df['col1'] #directly using this.

# df.loc[:, 'col1']  #retrieve using loc and column name

df.iloc[:,1]   #retrieve 2nd column

0    3
1    4
Name: col2, dtype: int64

## To convert series of list to one series. 

Use apply and stack method

In [61]:
_list = pd.Series({'col1': ['Red', 'Green', 'Black'], 'col2': ['Yellow', 'Orange'], 'col3': 'Black'})

_list

col1    [Red, Green, Black]
col2       [Yellow, Orange]
col3                  Black
dtype: object

In [62]:
d2 = _list.apply(pd.Series).stack().reset_index(drop= True)

d2

0       Red
1     Green
2     Black
3    Yellow
4    Orange
5     Black
dtype: object

In [192]:
s = pd.Series(['100', '1', 'python', '3.12', '400'])

w = pd.to_numeric(s, errors = 'coerce')

# w = s.tolist()

print('Before sorting', w)

drpna = w.dropna()

cnvrtd = drpna.astype(int)
    
nwcnvrtd = cnvrtd.sort_values()

print(nwcnvrtd)

Before sorting 0    100.00
1      1.00
2       NaN
3      3.12
4    400.00
dtype: float64
1      1
3      3
0    100
4    400
dtype: int64


In [194]:
newss = pd.concat([nwcnvrtd, pd.Series([500,'php'])], ignore_index= True)

newss

0      1
1      3
2    100
3    400
4    500
5    php
dtype: object

In [196]:
news1 = newss.loc[0:3]   #to get a subset of the original series.

news1

0      1
1      3
2    100
3    400
dtype: object

In [200]:
import pygwalker as pyg

df = pd.read_csv('./circuits.csv')
gwalker = pyg.walk(df)

ModuleNotFoundError: No module named 'pygwalker'

In [202]:
!pip list | grep pygwalker


In [203]:
temp = 'Python'
print(type(temp))

temp = 20
print(type(temp))

<class 'str'>
<class 'int'>


In [205]:
import math
math.fsum([0.01 for i in range(10)])

0.1

In [211]:
def test():
    x = 10
    print(x)
    x =+ 1 
    print(x)
test()

10
1


## To change the order of Series by changing the index 

Use reindex method

In [212]:
s = pd.Series([1,2,3,4,5,6,7], index = ['A','B','C', 'D', 'E', 'F', 'G'] )

s

A    1
B    2
C    3
D    4
E    5
F    6
G    7
dtype: int64

In [214]:
rei = s.reindex(index = ['B','A','D','C', 'E', 'F','G'])

rei

B    2
A    1
D    4
C    3
E    5
F    6
G    7
dtype: int64

## To find the mean and std deviation

Use mean and std function

In [229]:
s = pd.Series([1,2,3,4,5,6,7,8,9], index = ['a', 'b','c', 'd','e','f','g','h', 'i'])

print("\n The original series is: \n", s)

calme = s.mean()
print("\n The calculated mean is", calme)

calstd = s.std()

adjustdval = round(calstd,2)   #use round function to round the decimal places to two.


print("\n Te calculated std deviation is:", adjustdval)


 The original series is: 
 a    1
b    2
c    3
d    4
e    5
f    6
g    7
h    8
i    9
dtype: int64

 The calculated mean is 5.0

 Te calculated std deviation is: 2.74


In [230]:
index = pd.MultiIndex.from_tuples([('A', 1), ('A', 2), ('B', 1), ('B', 2)])
s = pd.Series([10, 20, 30, 40], index=index)

s

A  1    10
   2    20
B  1    30
   2    40
dtype: int64

In [232]:
df = pd.DataFrame({'values': [10, 20, 30]}, index=['a', 'b', 'c'])
df.set_index('values', inplace=True)

print(df)


Empty DataFrame
Columns: []
Index: [10, 20, 30]


In [233]:
s1 = pd.Series([1,2,3,4,5,6,7,8,9])

print('Series1 is:\n', s1)

s2 = pd.Series([2,4,6,8,10,12])

print('Series2 is:\n', s2)


Series1 is:
 0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int64
Series2 is:
 0     2
1     4
2     6
3     8
4    10
5    12
dtype: int64


## To find common and uncommon elements in a series

In [255]:
inter = [set(s1) & set(s2)]    # common elements

inter

[{2, 4, 6, 8}]

In [261]:
(set(s1).intersection(set(s2)))  #another method to find commmon elements


{2, 4, 6, 8}

In [263]:
inter = np.intersect1d(s1,s2) #another method to find commmon elements

inter

array([2, 4, 6, 8])

In [264]:
uncommon = set(s1) - set(s2)   #uncommon elements

uncommon

{1, 3, 5, 7, 9}

In [278]:
uncommon1 = s1[~s1.isin(s2)]  #another method to find uncommon elements.
uncommon1

0    1
2    3
4    5
6    7
8    9
dtype: int64

In [280]:
uncommon_elements = [x for x in s1 if x not in s2]      ###this method compares indexes. 

s1, s2, uncommon_elements       

(0    1
 1    2
 2    3
 3    4
 4    5
 5    6
 6    7
 7    8
 8    9
 dtype: int64,
 0     2
 1     4
 2     6
 3     8
 4    10
 5    12
 dtype: int64,
 [6, 7, 8, 9])

In [281]:
s1,s2

(0    1
 1    2
 2    3
 3    4
 4    5
 5    6
 6    7
 7    8
 8    9
 dtype: int64,
 0     2
 1     4
 2     6
 3     8
 4    10
 5    12
 dtype: int64)

## Elements not common in two series

In [286]:
uni = np.union1d(s1,s2)

uni

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 12])

In [287]:
inter1 = np.intersect1d(s1,s2)

inter1

array([2, 4, 6, 8])

In [290]:
uncom = set(uni) - set(inter1)

uncom

{1, 3, 5, 7, 9, 10, 12}

## To compute the minimum, 25th percentile, median, 75th, and maximum of a given series.

In [294]:
new_state = np.random.RandomState(100)

new_state

RandomState(MT19937) at 0x7FED0079CA40

In [301]:
num_sries = pd.Series(new_state.normal(10,4,20))

num_sries

0      3.837536
1     18.186856
2      4.412003
3      5.611312
4      9.045149
5      4.283732
6     13.796019
7      9.922410
8     13.578391
9     13.038772
10     4.009118
11     5.224456
12    15.185050
13    13.809103
14     5.130983
15     9.370939
16     3.969659
17    10.431537
18    12.988223
19    11.718706
dtype: float64

In [302]:
result = np.percentile(num_sries, q = [0,25,50,75,100])

print(result)

[ 3.8375359   4.95123826  9.64667449 13.17367707 18.18685587]


## To calculate the frequency of a given series elements

In [315]:
qw = pd.Series([1,2,1,2,2,3,4,5,6,7,8,9,10,5,7,8,9,0,10])

qw.value_counts().to_dict()       #to count freq.

{2: 3, 1: 2, 5: 2, 7: 2, 8: 2, 9: 2, 10: 2, 3: 1, 4: 1, 6: 1, 0: 1}

In [310]:
freq = {}

for x in qw:
    if x in freq:
        freq[x] += 1
    else:
        freq[x] = 1
print(freq)

######above code can be replaced by single line code. i.e. qw.value_counts().to_dict()  ############


most_freq = max(freq, key=freq.get)    #to get the element that is repeated most number of times.

new_qw = qw.apply(lambda x: most_freq if freq[x] == freq[most_freq] else 'Others')

print("\n New series:", new_qw)

{1: 2, 2: 3, 3: 1, 4: 1, 5: 2, 6: 1, 7: 2, 8: 2, 9: 2, 10: 2, 0: 1}

 New series: 0     Others
1          2
2     Others
3          2
4          2
5     Others
6     Others
7     Others
8     Others
9     Others
10    Others
11    Others
12    Others
13    Others
14    Others
15    Others
16    Others
17    Others
18    Others
dtype: object


   ## To get the positions of items of a given series in another given series

In [5]:
#to find out the position of ss2 in ss1.

ss1 = pd.Series([1,2,3,4,5,6,7,8,9,10])

ss2 = pd.Series([2,3,4,5,6,7,8,9,10])  

index_ss1 = pd.Index(ss1)
getpos = [pd.Index(ss1).get_loc(i) for i in ss2]

print(getpos)

NameError: name 'pd' is not defined

## Convert  first and last word of a string to uppercase

In [330]:
as1 = pd.Series(['abc','def', 'AjaY', 'Deepak', 'ajaY', 'ajay'])

as2 = as1.map(lambda x: x[0].upper() + x[1:-1] + x[-1].upper())

print(as2)

0       AbC
1       DeF
2      AjaY
3    DeepaK
4      AjaY
5      AjaY
dtype: object


In [331]:
az = pd.Series(['xx', 'xxx','xxxx', 'sxDcvc', 'xxXXXX', 'xxSXXXXX'])

az1 = az.map(lambda x: len(x)) ##to calculate number of characters in a given string

az1

0    2
1    3
2    4
3    6
4    6
5    8
dtype: int64

In [332]:
ag = pd.Series([1, 11, 13, 10, 67, 32])

ag1 = ag.diff().diff().tolist()  #to find diff of diff of the consecutive integers in a series of list.

ag1

[nan, nan, -8.0, -5.0, 60.0, -92.0]

## To find vowels

First lets take a look at the ways to split strings

In [356]:
vow = pd.Series(['apple', 'banana', 'orange', 'AvocadO', 'Olive Oil'])

vow

0        apple
1       banana
2       orange
3      AvocadO
4    Olive Oil
dtype: object

In [341]:
splitted = vow.str.split(' ', expand = True).stack()

splitted.reset_index()

level_0  level_1        0
0        0        0    apple
1        1        0   banana
2        2        0   orange
3        3        0  AvocadO
4        4        0    Olive
5        4        1      Oil

In [349]:
splitted1 = vow.apply(lambda x: x.split()).explode()
splitted1.reset_index(drop= True)

0      apple
1     banana
2     orange
3    AvocadO
4      Olive
5        Oil
dtype: object

## Final program

In [359]:
import re

def countwords(word):   
    return len(re.findall(r'[aeiouAEIOU]', word)) #to find any number of vowels in a string.


wordSeries = vow[vow.apply(countwords) >=3]  #this is to specify how many number of vowels are you looking for in your string.

print (wordSeries)

1       banana
2       orange
3      AvocadO
4    Olive Oil
dtype: object


In [8]:
import numpy as np
aar1 = np.array([[1,2], [3,4]])

aar2 = np.array([[5,6],[7,8], [9,10]])

new_arr = np.concatenate((aar1,aar2), axis =0)
new_arr

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [12]:
a = np.array([1, 2, 3, 4, 5, 6])

a.shape

a

array([1, 2, 3, 4, 5, 6])

In [11]:
a2 = a[np.newaxis, :]
a2.shape

a2

array([[1, 2, 3, 4, 5, 6]])

In [14]:
a3 = a[:, np.newaxis]

a3

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [18]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [19]:
print(a[a>=10])

[10 11 12]


In [24]:
xyz = a[(a>5) | (a==1)]

print(xyz)

[ 1  6  7  8  9 10 11 12]


In [27]:
b = np.nonzero(a<9)

b

(array([0, 0, 0, 0, 1, 1, 1, 1]), array([0, 1, 2, 3, 0, 1, 2, 3]))

In [28]:
b = np.array([[1, 1], [2, 2]])

b

array([[1, 1],
       [2, 2]])

In [29]:
data = np.array([[1, 2], [3, 4], [5, 6]])

data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [30]:
data[0:2, 0] #0th position at 0 and 1

array([1, 3])

In [7]:
import numpy as np
rng = np.random.default_rng(3)

rng.random((3,3)) #generates random 3,3 array.


array([[0.08564917, 0.23681051, 0.80127447],
       [0.58216204, 0.09412864, 0.43312694],
       [0.4790513 , 0.15973891, 0.73457715]])

In [9]:
rng.integers(10, size = (3,3))

array([[0, 1, 4],
       [3, 8, 5],
       [4, 4, 6]])

## How to access docstring

In [13]:
def double(a):
    '''Return a**2'''
    return a**2

double?   #to access docstring use ?, or ?? for more information.

In [14]:
double??

In [15]:
a3D = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

a3D

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [26]:
np.arange(2, 10, 2)

array([2, 4, 6, 8])

In [21]:
np.linspace(2., 5., 5)

array([2.  , 2.75, 3.5 , 4.25, 5.  ])

In [27]:
np.eye(3,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [37]:
A = np.ones((2,2))
C = np.zeros((2,2))
B = np.eye(2,2)
D = np.diag((-3,-4))

combnd_arr = np.block([[A, B], [C, D]])

combnd_arr

array([[ 1.,  1.,  1.,  0.],
       [ 1.,  1.,  0.,  1.],
       [ 0.,  0., -3.,  0.],
       [ 0.,  0.,  0., -4.]])

In [32]:
A = np.ones((2, 2))
B = np.eye(2, 2)
C = np.zeros((2, 2))
D = np.diag((-3, -4))
np.block([[A, B], [C, D]])

array([[ 1.,  1.,  1.,  0.],
       [ 1.,  1.,  0.,  1.],
       [ 0.,  0., -3.,  0.],
       [ 0.,  0.,  0., -4.]])

In [1]:
import numpy as np

np?

In [7]:
x3 = np.random.randint(10, size=(3,4,5)) # this size = block size,row size, column size

x3

array([[[6, 9, 3, 8, 0],
        [4, 3, 5, 2, 4],
        [4, 4, 3, 8, 1],
        [4, 0, 2, 4, 6]],

       [[3, 4, 3, 7, 2],
        [2, 6, 2, 2, 7],
        [5, 1, 9, 6, 7],
        [5, 0, 0, 8, 3]],

       [[4, 7, 3, 3, 8],
        [1, 4, 2, 9, 0],
        [3, 7, 2, 1, 4],
        [2, 9, 1, 4, 6]]])